export const PerformerAttributesLabelMapping: Record<string, string> = {
    unionId: "Union ID",
    socialInsuranceNumber: "SIN",
    city: "City",
    state: "Province",
    postalCode: "Postal Code",
    country: "Country",
    selfDrive: "Self Drive",
    gender: "Gender",
    ethnicity: "Ethnicity",
    hairColor: "Hair Color",
    eyeColor: "Eye Color",
    sizeHeight: "Height",
    sizeWeight: "Weight",
    sizeChest: "Chest Size",
    sizeJacket: "Jacket Size",
    sizeDress: "Dress Size",
    sizeBustCup: "Bust Cup Size",
    sizeBustBand: "Bra Size",
    sizeWaist: "Waist Size",
    sizeHips: "Hip Size",
    sizeShoe: "Shoe Size",
    sizeInseam: "Inseam",
    sizeSleeve: "Sleeve Size",
    sizeNeck: "Neck Size",
    sizeHat: "Hat Size",
    emergencyFullName: "Emergency Name",
    emergencyTel: "Emergency Tel",
};
