import {PerformerProfileType} from "../types/PerformerProfileType.tsx";
import {LocalUserType} from "../types/LocalUserType.tsx";

export const emptyProfile: PerformerProfileType = {
    keyName: "",
    fullBodyKeyName: "",
    documentKeyName: "",
    actraCardKeyName: "",
    whasaKeyName: "",
    firstName: "",
    middleName: "",
    lastName: "",
    unionStatus: "",
    unionId: "",
    dateOfBirth: "",
    guardianFullName: "",
    guardianTel: "",
    socialInsuranceNumber: "",
    emergencyFullName: "",
    emergencyTel: "",
    city: "",
    state: "",
    postalCode: "",
    country: "Canada",
    selfDrive: false,
    gender: "",
    ethnicity: "",
    lgbt: false,
    bipoc: false,
    trans: false,
    visibleTattoos: false,
    hairColor: "",
    eyeColor: "",
    sizeHeight: 0,
    sizeWeight: 0,
    sizeChest: 0,
    sizeWaist: 0,
    sizeHips: 0,
    sizeShoe: 0,
    sizeInseam: 0,
    sizeSleeve: 0,
    sizeNeck: 0,
    sizeHat: 0,
    sizeJacket: "",
    sizeBustCup: "",
    sizeBustBand: 0,
    sizeDress: "",
};

// Пустой пользователь
export const emptyUser: LocalUserType = {
    id: "",
    tel: "",
    email: "",
    password: "",
    emailVerified: false,
    testPassed: false,
    userActivated: false,
    reason: "",
    profile: emptyProfile,
    submissionPending: false,
    productionDays: [],
    role: "Performer"
};